package StaticVariables;

import Enums.REGION;
import Enums.ROLE;
import TournamentComponents.Player;

public class Players {
	public static final Player Huni = new Player("Huni", 0.87f, ROLE.Top, REGION.KR, false);
	public static final Player Spica = new Player("Spica", 0.90f, ROLE.Jungle, REGION.NA, false);
	public static final Player PowerOfEvil = new Player("PowerOfEvil", 0.87f, ROLE.Mid, REGION.EU, true);
	public static final Player Lost = new Player("Lost", 0.82f, ROLE.Bottom, REGION.OCE, false);
	public static final Player SwordArt = new Player("SwordArt", 0.87f, ROLE.Support, REGION.SEA, true);
	public static final Player Keaiduo = new Player("Keaiduo", 0.85f, ROLE.Mid, REGION.CN, true);
	public static final Player Shenyi = new Player("Shenyi", 0.86f, ROLE.Support, REGION.CN, true);
	public static final Player Impact = new Player("Impact", 0.88f, ROLE.Top, REGION.KR, false);
	public static final Player Contractz = new Player("Contractz", 0.83f, ROLE.Jungle, REGION.NA, false);
	public static final Player Svenskeren = new Player("Svenskeren", 0.82f, ROLE.Jungle, REGION.EU, false);
	public static final Player Jiizuke = new Player("Jiizuke", 0.88f, ROLE.Mid, REGION.EU, true);
	public static final Player Danny = new Player("Danny", 0.85f, ROLE.Bottom, REGION.NA, false);
	public static final Player IgNar = new Player("IgNar", 0.86f, ROLE.Support, REGION.KR, true);
	public static final Player Jojopyun = new Player("jojopyun", 0.80f, ROLE.Mid, REGION.NA, false);
	public static final Player Fudge = new Player("Fudge", 0.84f, ROLE.Mid, REGION.OCE, false);
	public static final Player Blaber = new Player("Blaber", 0.89f, ROLE.Jungle, REGION.NA, false);
	public static final Player Perkz = new Player("Perkz", 0.85f, ROLE.Mid, REGION.EU, true);
	public static final Player Zven = new Player("Zven", 0.90f, ROLE.Bottom, REGION.EU, true);
	public static final Player Vulcan = new Player("Vulcan", 0.89f, ROLE.Support, REGION.NA, false);
	public static final Player Summit = new Player("Summit", 0.91f, ROLE.Top, REGION.KR, true);
	public static final Player Berserker = new Player("Berserker", 0.90f, ROLE.Bottom, REGION.NA, false);
	public static final Player Winsome = new Player("Winsome", 0.80f, ROLE.Support, REGION.KR, true);
	public static final Player Finn = new Player("Finn", 0.81f, ROLE.Top, REGION.EU, true);
	public static final Player Broxah = new Player("Broxah", 0.78f, ROLE.Jungle, REGION.EU, true);
	public static final Player Pobelter = new Player("Pobelter", 0.74f, ROLE.Mid, REGION.NA, false);
	public static final Player Damonte = new Player("Damonte", 0.75f, ROLE.Mid, REGION.NA, false);
	public static final Player WildTurtle = new Player("WildTurtle", 0.84f, ROLE.Bottom, REGION.NA, false);
	public static final Player Smoothie = new Player("Smoothie", 0.71f, ROLE.Support, REGION.NA, false);
	public static final Player Jenkins = new Player("Jenkins", 0.81f, ROLE.Top, REGION.NA, false);
	public static final Player Alphari = new Player("Alphari", 0.94f, ROLE.Top, REGION.EU, true);
	public static final Player Santorin = new Player("Santorin", 0.87f, ROLE.Jungle, REGION.EU, false);
	public static final Player Jensen = new Player("Jensen", 0.89f, ROLE.Mid, REGION.EU, false);
	public static final Player Tactical = new Player("Tactical", 0.89f, ROLE.Bottom, REGION.NA, false);
	public static final Player CoreJJ = new Player("CoreJJ", 0.94f, ROLE.Support, REGION.KR, true);
	public static final Player Licorice = new Player("Licorice", 0.84f, ROLE.Top, REGION.NA, false);
	public static final Player Iconic = new Player("Iconic", 0.75f, ROLE.Jungle, REGION.NA, false);
	public static final Player AblazeOlive = new Player("AblazeOlive", 0.83f, ROLE.Mid, REGION.NA, false);
	public static final Player Stixxay = new Player("Stixxay", 0.81f, ROLE.Bottom, REGION.NA, false);
	public static final Player Chime = new Player("Chime", 0.78f, ROLE.Support, REGION.NA, false);
	public static final Player Pridestalkr = new Player("Pridestalkr", 0.81f, ROLE.Jungle, REGION.EU, true);
	public static final Player Olleh = new Player("Olleh", 0.84f, ROLE.Support, REGION.KR, true);
	public static final Player Ssumday = new Player("Ssumday", 0.85f, ROLE.Top, REGION.KR, false);
	public static final Player Closer = new Player("Closer", 0.92f, ROLE.Jungle, REGION.EU, true);
	public static final Player Abbedagge = new Player("Abbedagge", 0.91f, ROLE.Mid, REGION.EU, true);
	public static final Player FBI = new Player("FBI", 0.92f, ROLE.Bottom, REGION.OCE, false);
	public static final Player Huhi = new Player("Huhi", 0.90f, ROLE.Support, REGION.KR, false);
	public static final Player FakeGod = new Player("FakeGod", 0.79f, ROLE.Top, REGION.NA, false);
	public static final Player Akaadian = new Player("Akaadian", 0.82f, ROLE.Jungle, REGION.NA, false);
	public static final Player Yusui = new Player("Yusui", 0.68f, ROLE.Mid, REGION.NA, false);
	public static final Player Neo = new Player("Neo", 0.85f, ROLE.Bottom, REGION.NA, false);
	public static final Player Aphromoo = new Player("Aphromoo", 0.85f, ROLE.Support, REGION.NA, false);
	public static final Player River = new Player("River", 0.85f, ROLE.Jungle, REGION.SEA, true);
	public static final Player Biofrost = new Player("Biofrost", 0.79f, ROLE.Support, REGION.NA, false);
	public static final Player Revenge = new Player("Revenge", 0.82f, ROLE.Top, REGION.NA, false);
	public static final Player Xerxe = new Player("Xerxe", 0.83f, ROLE.Jungle, REGION.EU, true);
	public static final Player Insanity = new Player("Insanity", 0.83f, ROLE.Mid, REGION.NA, false);
	public static final Player Raes = new Player("Raes", 0.70f, ROLE.Bottom, REGION.OCE, false);
	public static final Player Destiny = new Player("Destiny", 0.83f, ROLE.Support, REGION.OCE, false);
	public static final Player Kumo = new Player("Kumo", 0.77f, ROLE.Top, REGION.NA, false);
	public static final Player Josedeodo = new Player("Josedeodo", 0.82f, ROLE.Jungle, REGION.LAN, true);
	public static final Player Palafox = new Player("Palafox", 0.82f, ROLE.Mid, REGION.NA, false);
	public static final Player Johnsun = new Player("Johnsun", 0.82f, ROLE.Bottom, REGION.NA, false);
	public static final Player Dreams = new Player("Dreams", 0.73f, ROLE.Support, REGION.KR, true);
	public static final Player Toucouille = new Player("Toucouille", 0.80f, ROLE.Mid, REGION.EU, true);
	public static final Player Bjergsen = new Player("Bjergsen", 0.93f, ROLE.Mid, REGION.EU, false);
	public static final Player Yeon = new Player("Yeon", 0.80f, ROLE.Bottom, REGION.NA, false);
	public static final Player Eyla = new Player("Eyla", 0.83f, ROLE.Support, REGION.OCE, false);
	public static final Player Tenacity = new Player("Tenacity", 0.78f, ROLE.Top, REGION.NA, false);
	public static final Player Kenvi = new Player("Kenvi", 0.81f, ROLE.Jungle, REGION.NA, false);
	public static final Player Luger = new Player("Luger", 0.86f, ROLE.Bottom, REGION.EU, true);
	public static final Player Poome = new Player("Poome", 0.80f, ROLE.Support, REGION.NA, false);
	public static final Player Cabochard = new Player("Cabochard", 0.89f, ROLE.Top, REGION.EU, true);
	public static final Player Prismal = new Player("Prismal", 0.82f, ROLE.Bottom, REGION.NA, false);
	public static final Player Wunder = new Player("Wunder", 0.86f, ROLE.Top, REGION.EU, false);
	public static final Player Jankos = new Player("Jankos", 0.95f, ROLE.Jungle, REGION.EU, false);
	public static final Player Caps = new Player("Caps", 0.92f, ROLE.Mid, REGION.EU, false);
	public static final Player Rekkles = new Player("Rekkles", 0.90f, ROLE.Bottom, REGION.EU, false);
	public static final Player Mikyx = new Player("Mikyx", 0.88f, ROLE.Support, REGION.EU, false);
	public static final Player Adam = new Player("Adam", 0.87f, ROLE.Top, REGION.EU, false);
	public static final Player Bwipo = new Player("Bwipo", 0.89f, ROLE.Top, REGION.EU, true);
	public static final Player Nisqy = new Player("Nisqy", 0.90f, ROLE.Mid, REGION.EU, false);
	public static final Player Upset = new Player("Upset", 0.95f, ROLE.Bottom, REGION.EU, false);
	public static final Player Hyllisang = new Player("Hyllisang", 0.96f, ROLE.Support, REGION.EU, false);
	public static final Player Odoamne = new Player("Odoamne", 0.88f, ROLE.Top, REGION.EU, false);
	public static final Player Inspired = new Player("Inspired", 0.88f, ROLE.Jungle, REGION.EU, false);
	public static final Player Larssen = new Player("Larssen", 0.89f, ROLE.Mid, REGION.EU, false);
	public static final Player HansSama = new Player("Hans Sama", 0.92f, ROLE.Bottom, REGION.EU, false);
	public static final Player Trymbi = new Player("Trymbi", 0.89f, ROLE.Support, REGION.EU, false);
	public static final Player Szygenda = new Player("Szygenda", 0.79f, ROLE.Top, REGION.EU, false);
	public static final Player Selfmade = new Player("Selfmade", 0.88f, ROLE.Jungle, REGION.EU, false);
	public static final Player LIDER = new Player("LIDER", 0.82f, ROLE.Mid, REGION.EU, false);
	public static final Player Crownshot = new Player("Crownshot", 0.79f, ROLE.Bottom, REGION.EU, false);
	public static final Player Labrov = new Player("Labrov", 0.85f, ROLE.Support, REGION.EU, false);
	public static final Player HiRit = new Player("HiRit", 0.86f, ROLE.Top, REGION.KR, true);
	public static final Player Razork = new Player("Razork", 0.89f, ROLE.Jungle, REGION.EU, false);
	public static final Player Vetheo = new Player("Vetheo", 0.92f, ROLE.Mid, REGION.EU, false);
	public static final Player Kobbe = new Player("Kobbe", 0.79f, ROLE.Bottom, REGION.EU, false);
	public static final Player Vander = new Player("Vander", 0.84f, ROLE.Support, REGION.EU, false);
	public static final Player BrokenBlade = new Player("Broken Blade", 0.89f, ROLE.Top, REGION.EU, false);
	public static final Player Kirei = new Player("Kirei", 0.58f, ROLE.Jungle, REGION.EU, false);
	public static final Player NuclearInt = new Player("NuclearInt", 0.80f, ROLE.Mid, REGION.EU, false);
	public static final Player Neon = new Player("Neon", 0.74f, ROLE.Bottom, REGION.EU, false);
	public static final Player Limit = new Player("Limit", 0.77f, ROLE.Support, REGION.EU, false);
	public static final Player Armut = new Player("Armut", 0.92f, ROLE.Top, REGION.EU, false);
	public static final Player Elyoya = new Player("Elyoya", 0.95f, ROLE.Jungle, REGION.EU, false);
	public static final Player Humanoid = new Player("Humanoid", 0.93f, ROLE.Mid, REGION.EU, false);
	public static final Player Carzzy = new Player("Carzzy", 0.92f, ROLE.Bottom, REGION.EU, false);
	public static final Player Kaiser = new Player("Kaiser", 0.95f, ROLE.Support, REGION.EU, false);
	public static final Player Jenax = new Player("Jenax", 0.81f, ROLE.Top, REGION.EU, false);
	public static final Player Treatz = new Player("Treatz", 0.87f, ROLE.Support, REGION.EU, false);
	public static final Player Blue = new Player("Blue", 0.75f, ROLE.Mid, REGION.EU, false);
	public static final Player Jezu = new Player("Jezu", 0.80f, ROLE.Bottom, REGION.EU, false);
	public static final Player Lillip = new Player("Lillip", 0.78f, ROLE.Support, REGION.EU, false);
	public static final Player WhiteKnight = new Player("WhiteKnight", 0.84f, ROLE.Top, REGION.EU, false);
	public static final Player Zanzarah = new Player("Zanzarah", 0.75f, ROLE.Jungle, REGION.EU, false);
	public static final Player MagiFelix = new Player("MagiFelix", 0.83f, ROLE.Mid, REGION.EU, false);
	public static final Player Jeskla = new Player("Jeskla", 0.80f, ROLE.Bottom, REGION.EU, false);
	public static final Player Promisq = new Player("Promisq", 0.70f, ROLE.Support, REGION.EU, false);
	public static final Player Kryze = new Player("Kryze", 0.80f, ROLE.Top, REGION.EU, false);
	public static final Player Markoon = new Player("Markoon", 0.83f, ROLE.Jungle, REGION.EU, false);
	public static final Player Nukeduck = new Player("Nukeduck", 0.83f, ROLE.Mid, REGION.EU, false);
	public static final Player Patrik = new Player("Patrik", 0.88f, ROLE.Bottom, REGION.EU, false);
	public static final Player Advienne = new Player("Advienne", 0.82f, ROLE.Support, REGION.EU, false);
	
	public static final Player Flakked = new Player("Flakked", 0.82f, ROLE.Bottom, REGION.EU, false);
	public static final Player Targamas = new Player("Targamas", 0.82f, ROLE.Support, REGION.EU, false);
	
	public static final Player Malrang = new Player("Malrang", 0.83f, ROLE.Jungle, REGION.KR, true);
	public static final Player Comp = new Player("Comp", 0.84f, ROLE.Bottom, REGION.EU, false);
	
	public static final Player Shaltan = new Player("Shaltan", 0.81f, ROLE.Jungle, REGION.EU, false);
	
	public static final Player Sertuss = new Player("Sertuss", 0.80f, ROLE.Mid, REGION.EU, false);
	public static final Player Gilius = new Player("Gilius", 0.83f, ROLE.Jungle, REGION.EU, false);
	
	public static final Player Dajor = new Player("Dajor", 0.77f, ROLE.Mid, REGION.EU, false);
	
	public static final Player Cinkrof = new Player("Cinkrof", 0.83f, ROLE.Jungle, REGION.EU, false);
	public static final Player xMatty = new Player("xMatty", 0.81f, ROLE.Bottom, REGION.EU, false);
	
	public static final Player RKR = new Player("RKR", 0.84f, ROLE.Mid, REGION.EU, false);
	public static final Player UNFORG1VEN = new Player("UNFORG1VEN", 0.78f, ROLE.Bottom, REGION.EU, false);

}
